from odoo import api, models, fields, _


class UserMarginConfigurations(models.Model):
    _inherit = ['res.users']
    # _inherit = ['mail.thread', 'mail.activity.mixin']
    # _name = 'lgps.user_margin_configuration'

    # name = fields.Char(
    #     required=True,
    #     string=_("Internal Id"),
    #     default="Autogenerated on Save",
    # )

    min_margin = fields.Float(
        string=_("Min Margin"),
        digits=(2, 2),
        help=_('Min Margin expected for this user in Sales Orders')
    )

    skip_min_margin_rule = fields.Boolean(
        string=_("Skip Margin Rule"),
        default=False,
        help=_('Allow to sell with negative margin')
    )

    # res_user_id = fields.Many2one(
    #      comodel_name="res.users",
    #      required=True,
    #      string=_("Usuario a configurar"),
    #      index=True,
    # )

    # @api.model
    # def create(self, vals):
    #     seq = self.env['ir.sequence'].next_by_code('lgps.user_margin_configuration') or _('New')
    #     vals['name'] = seq
    #     return super(UserMarginConfigurations, self).create(vals)
