# -*- coding: utf-8 -*-
from odoo import api, models, fields, _


class TrackingLogs(models.Model):
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _name = 'lgps.tracking_logs'

    name = fields.Char(
        required=True,
        string=_("Tracking Id"),
        default="Autogenerated on Save"
    )

    comment = fields.Text(
        string=_("Commentary"),
        required=True,
    )

    comment_date = fields.Datetime(
        default=fields.Datetime.now,
        string=_("Comment Date"),
        required=True,
    )

    employee_id = fields.Many2one(
        comodel_name="hr.employee",
        string=_("Monitorist"),
        required=True,
    )

    email_sent = fields.Html(
        string=_("Email sent"),
        readonly=True
    )

    tracking_id = fields.Many2one(
        comodel_name="lgps.tracking",
        ondelete="set null",
        string=_("Tracking"),
        required=True,
    )

    @api.model
    def create(self, vals):
        seq = self.env['ir.sequence'].next_by_code('lgps.tracking_logs') or '/'
        vals['name'] = seq
        return super(TrackingLogs, self).create(vals)
